name: Lint

on: [push, pull_request]

permissions: read-all

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        working-directory: [ "", "testing" ]
    runs-on: ubuntu-latest
    name: Lint (${{ matrix.working-directory != '' && matrix.working-directory || 'repository root' }})
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - name: Check that go.mod is tidied
        if: always()
        run: go mod tidy -diff
        working-directory: ${{ matrix.working-directory }}
      - name: golangci-lint
        if: always()
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.1
          working-directory: ${{ matrix.working-directory }}
