name: Tests

on: [push, pull_request]

permissions: read-all

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit tests
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          check-latest: true
      - name: Unit tests (repository root)
        run: go test -shuffle=on -v ./...
      - name: Unit tests (testing/)
        run: go test -shuffle=on -v ./...
        working-directory: testing
